### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 6stitch9** [AstraaDev/Discord-Token-AutoLogin#1]
Traceback (most recent call last):
  File "A:\ok\loging in.py", line 38, in <module>
    driver = webdriver.Chrome('chromedriver.exe')
  File "A:\ok\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "A:\ok\venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 89, in __init__
    self.service.start()
  File "A:\ok\venv\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

i get that when i try to run it. GUI pops up n all but this happens after i click enter. I am trying to use this since it appears logging in thorugh inspect element no longer works. Does anyone have a fix

**Comment by 6stitch9** [comment]
wait i think it need to install the chrome driver file, im just looking for proof that this is safe since github isnt showing source code. I trust this guy and have used code from some of his other projects but just makeing sure, and all i need to do is instal that right?

**Comment by AstraaDev** [comment]
Indeed, you do not need to install anything else!
Concerning the chromedriver you can install it by yourself from their [website](https://chromedriver.chromium.org).
Otherwise you can simply use my All-Tool-In-One, the current version is more recent even if it requires a small upgrade...
